pipeline_name: dd_pusht
mode: finetune
seed: 0
device: cuda:0

# Task
task:
  env_name: pusht-keypoints-v0
  horizon: 16
env_name: pusht-keypoints-v0
horizon: 16
dataset_path: /n/home04/hangle/data/pusht/pusht_cchi_v7_replay.zarr
max_episode_steps: 300
obs_keys: ["state", "action", "keypoint"]
obs_dim: 20
act_dim: 2
target_return: 0.95
w_cfg: 0.0
obs_steps: 2
action_steps: 8
abs_action: false

# Environment
terminal_penalty: 0.0 # pusht task does not penalize early termination
discount: 1.0 # short horizon, dense rewards
damping: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
#damping: [0.0, 0.1, 0.2, 0.3, 0.4]
#damping: [0.0]
#gravity: [0.0, 5.0, 10.0, 15.0, 20.0, 25.0]

# DD
solver: ddim

# Network Architecture, use DiT
emb_dim: 128
d_model: 256
n_heads: 8
depth: 2
label_dropout: 0.15
sampling_steps: 20
predict_noise: True
next_obs_loss_weight: 5.0
ema_rate: 0.99

# Training
diffusion_gradient_steps: 1000000
invdyn_gradient_steps: 200000
batch_size: 128
log_interval: 1000
save_interval: 50000

# Forward model


# Inference
#diffusion_ckpt: latest
#invdyn_ckpt: latest
diffusion_ckpt: 300000
invdyn_ckpt: 300000
num_envs: 1
eval_episodes: 50
eval_interval: 50000 
temperature: 0.5
use_ema: True
save_video: true
success_threshold: 0.95
warm_start: True
save_model_folder: placeholder 

# Fine-tuning
save_ft_path: ft_data
invdyn_gradient_steps_ft: 20000
ft_save_interval: 5000

# Fine-tuning the planner
k_sample: 16
best_k: 4
diffusion_gradient_steps_ft: 50000
save_interval_planner_ft: 10000

# Forward model
fm_gradient_steps: 10000
fm_save_interval: 5000
fm_gradient_steps_ft: 5000
fm_ckpt: latest

# hydra
hydra:
  job:
    chdir: false
  
# wandb
project: PlayAdaptation
name: ${project}_${now:%Y%m%d_%H%M%S}
exp_name: ${env_name}_${solver}_sample_${sampling_steps}_horizon_${horizon}
save_path: logs
wandb_mode: offline
group: dd_pusht
work_dir: ${save_path}/${pipeline_name}/${mode}/${env_name}/${exp_name}_${now:%Y%m%d_%H%M%S}/${seed}